"""add streak monior columns to user table

Revision ID: 4e73de03b0be
Revises: f1e7cdca2cdf
Create Date: 2026-03-25 09:14:06.644664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e73de03b0be"
down_revision: Union[str, Sequence[str], None] = "f1e7cdca2cdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("current_streak", sa.Integer(), nullable=True, default=0)
    )
    op.add_column(
        "users", sa.Column("longest_streak", sa.Integer(), nullable=True, default=0)
    )
    op.add_column("users", sa.Column("last_active_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_active_date")
    op.drop_column("users", "longest_streak")
    op.drop_column("users", "current_streak")
    # ### end Alembic commands ###
