"""create exercise_answers table

Revision ID: 5db7f7b41218
Revises: c48110d6d298
Create Date: 2026-03-25 07:16:53.959102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db7f7b41218'
down_revision: Union[str, Sequence[str], None] = 'c48110d6d298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'user_id', name='uq_unit_user')
    )
    op.create_index(op.f('ix_exercise_answers_unit_id'), 'exercise_answers', ['unit_id'], unique=False)
    op.create_index(op.f('ix_exercise_answers_user_id'), 'exercise_answers', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_users_unit_id'), 'reading_answers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_unit_id'), 'reading_answers', ['user_id', 'unit_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_exercise_answers_user_id'), table_name='exercise_answers')
    op.drop_index(op.f('ix_exercise_answers_unit_id'), table_name='exercise_answers')
    op.drop_table('exercise_answers')
    # ### end Alembic commands ###
