"""create reading answer table

Revision ID: 7490133f6032
Revises: 66bb172db42d
Create Date: 2026-03-21 00:45:04.730159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7490133f6032'
down_revision: Union[str, Sequence[str], None] = '66bb172db42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_answers_unit_id'), 'reading_answers', ['unit_id'], unique=False)
    op.create_index(op.f('ix_reading_answers_user_id'), 'reading_answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_answers_user_id'), table_name='reading_answers')
    op.drop_index(op.f('ix_reading_answers_unit_id'), table_name='reading_answers')
    op.drop_table('reading_answers')
    # ### end Alembic commands ###
