"""add created at column to reading_answers table

Revision ID: 92a415062945
Revises: 7490133f6032
Create Date: 2026-03-21 01:03:00.297445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a415062945'
down_revision: Union[str, Sequence[str], None] = '7490133f6032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_answers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('reading_answers', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reading_answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reading_answers', 'unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reading_answers', 'created_at')
    # ### end Alembic commands ###
