"""add learned words table

Revision ID: c8a77b904882
Revises: 4e73de03b0be
Create Date: 2026-03-25 16:32:05.402083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a77b904882'
down_revision: Union[str, Sequence[str], None] = '4e73de03b0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_index(op.f('ix_learned_words_user_id'), 'learned_words', ['user_id'], unique=False)
    op.create_index(op.f('ix_learned_words_word_id'), 'learned_words', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learned_words_word_id'), table_name='learned_words')
    op.drop_index(op.f('ix_learned_words_user_id'), table_name='learned_words')
    op.drop_table('learned_words')
    # ### end Alembic commands ###
